# -*- coding: utf-8 -*-
"""Untitled15.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGKmmvDU1BXBoTSaTnVxHj5zlMg7hIf7
"""

!pip install tensorflow pandas numpy matplotlib scikit-learn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re, io, zipfile, requests

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

np.random.seed(42)
tf.random.set_seed(42)
print('Libraries imported.')

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip'
response = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(response.content))
with z.open('SMSSpamCollection') as f:
    df = pd.read_csv(f, sep='\t', header=None, names=['label', 'message'])

print(f'Dataset shape : {df.shape}')
print(f'Label counts  :\n{df["label"].value_counts()}')
df.head(10)

df['label_enc'] = (df['label'] == 'spam').astype(int)

# Basic text cleaning
def clean_text(text):
    text = text.lower()                       # Lowercase
    text = re.sub(r'[^a-z0-9\s]', '', text)  # Remove special characters
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

df['clean_msg'] = df['message'].apply(clean_text)
print('Sample cleaned messages:')
print(df[['message', 'clean_msg', 'label_enc']].head(4))

MAX_VOCAB  = 10000   # Vocabulary size
MAX_LEN    = 100     # Pad/truncate all sequences to this length

# Tokenise text
tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token='<OOV>')
tokenizer.fit_on_texts(df['clean_msg'])

sequences = tokenizer.texts_to_sequences(df['clean_msg'])
X = pad_sequences(sequences, maxlen=MAX_LEN, padding='post', truncating='post')
y = df['label_enc'].values

print(f'Vocabulary size : {len(tokenizer.word_index)}')
print(f'X shape         : {X.shape}')
print(f'Sample sequence : {X[0][:20]} ...')

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f'Train: {X_train.shape}, Test: {X_test.shape}')

EMBED_DIM = 64
LSTM_UNITS = 64

model = keras.Sequential([
    layers.Embedding(MAX_VOCAB, EMBED_DIM, input_length=MAX_LEN, name='embedding'),
    layers.Bidirectional(
        layers.LSTM(LSTM_UNITS, dropout=0.2, recurrent_dropout=0.2),
        name='bilstm'
    ),
    layers.Dense(32, activation='relu', name='dense1'),
    layers.Dropout(0.4, name='dropout'),
    layers.Dense(1, activation='sigmoid', name='output')
], name='RNN_SpamDetector')

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=3, restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    epochs=8,
    batch_size=64,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f'Test Loss     : {test_loss:.4f}')
print(f'Test Accuracy : {test_acc * 100:.2f}%')

y_prob = model.predict(X_test).ravel()
y_pred = (y_prob >= 0.5).astype(int)

print()
print('Classification Report:')
print(classification_report(y_test, y_pred, target_names=['Ham', 'Spam']))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, metric, title in zip(axes,
                               [('accuracy', 'val_accuracy'), ('loss', 'val_loss')],
                               ['Accuracy', 'Loss']):
    ax.plot(history.history[metric[0]], label='Train', linewidth=2)
    ax.plot(history.history[metric[1]], label='Val',   linewidth=2, linestyle='--')
    ax.set_title(f'RNN LSTM — {title}', fontsize=13, fontweight='bold')
    ax.set_xlabel('Epoch'); ax.set_ylabel(title)
    ax.legend(); ax.grid(True, alpha=0.3)
plt.tight_layout(); plt.show()

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(cm, display_labels=['Ham', 'Spam'])
fig, ax = plt.subplots(figsize=(5, 4))
disp.plot(ax=ax, cmap='Reds', colorbar=False)
ax.set_title('RNN — Confusion Matrix', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

def predict_sms(message):
    cleaned = clean_text(message)
    seq = tokenizer.texts_to_sequences([cleaned])
    padded = pad_sequences(seq, maxlen=MAX_LEN, padding='post')
    prob = model.predict(padded, verbose=0)[0][0]
    label = 'SPAM' if prob >= 0.5 else 'HAM'
    print(f'Message : "{message}"')
    print(f'Prediction : {label}  (confidence: {prob:.4f})')
    print()

predict_sms('Congratulations! You have won a free iPhone. Click here to claim now!')
predict_sms('Hey, are you coming to the meeting at 3pm today?')
predict_sms('URGENT! Your bank account has been suspended. Call 08001234 immediately.')

